# Feel free to change the values.
# Changing the keys will require a modification of the ../src/main.cpp file
# to accomodate the changes. You will also need to re-compile the program.

# directories contains the directories that you want to have created.
# You may decide to include a path to a nested directory (e.g. "build/debug")

# tlfiles contains the top level files.
# The first item is its name and the second item is its contents.

# srcfiles contains the source files that you wish to include in directories.
# The first item has the path, the second item has the name and the third item its contents.

directories = ["src", "inc", "lib"]

files = [
[".gitignore",
'''
build/
'''
],
["CMakeLists.txt",
'''
'''
],
["README.md",
'''
'''
],
["COPYING",
'''
'''
],
[
"src/main.cpp", 
'''
#include <iostream>       

int main(int argc, char **argv) {

   std::cout << "Hello, world!\n";
   
   return 0;
}
'''
]
]

commands = ['''echo "Test"'''] # Commands to be executed by the system, such as git init
