# Feel free to change the values.
# Changing the keys will require a modification of the ../src/main.cpp file
# to accomodate the changes. You will also need to re-compile the program.

directories = ["src", "inc", "lib"]

tlfiles = [".gitignore", "CMakeLists.txt",
             "README.md", "COPYING"
          ] # Top level files such as .gitignore, CMakeLists.txt etc.

srcfiles = ["src/main.cpp"] # Files to be included into directories, such as main.cpp

commands = ["git init"] # Commands to be executed by the system, such as git init
