# Feel free to change the values.
# Changing the keys will require a modification of the ../src/main.cpp file
# to accomodate the changes. You will also need to re-compile the program.

directories = ["src", "inc", "lib"]

tlfiles = [[".gitignore", '''build/'''], ["CMakeLists.txt", ''' '''], # Top level files such as .gitignore, CMakeLists.txt etc.
             ["README.md", ''' '''], ["COPYING", ''' ''']
          ] 

srcfiles = [["src/", "main.cpp", # Each item in this list is another list. In that nested list, the first item is the the path, the second item is the name of the file and the third item is the actual contents.
'''#include <iostream>       

int main(int argc, char **argv {

   std::cout << "Hello, world!\n";
   
   return 0;
}
''']] # Files to be included into directories, such as main.cpp

commands = ["git init"] # Commands to be executed by the system, such as git init
